In [1]:
!pip install pandas pyarrow
# or !pip install pandas fastparquet

Requirement already satisfied: pandas in c:\users\laran\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: pyarrow in c:\users\laran\anaconda3\lib\site-packages (19.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\laran\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\laran\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\laran\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\laran\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\laran\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [134]:
import pandas as pd
df = pd.read_parquet("yellow_tripdata_2025-11.parquet")

In [135]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,7,2025-11-01 00:13:25,2025-11-01 00:13:25,1.0,1.68,1.0,N,43,186,1,14.9,0.00,0.5,1.50,0.00,1.0,22.15,2.5,0.00,0.75
1,2,2025-11-01 00:49:07,2025-11-01 01:01:22,1.0,2.28,1.0,N,142,237,1,14.2,1.00,0.5,4.99,0.00,1.0,24.94,2.5,0.00,0.75
2,1,2025-11-01 00:07:19,2025-11-01 00:20:41,0.0,2.70,1.0,N,163,238,1,15.6,4.25,0.5,4.27,0.00,1.0,25.62,2.5,0.00,0.75
3,2,2025-11-01 00:00:00,2025-11-01 01:01:03,3.0,12.87,1.0,N,138,261,1,66.7,6.00,0.5,0.00,6.94,1.0,86.14,2.5,1.75,0.75
4,1,2025-11-01 00:18:50,2025-11-01 00:49:32,0.0,8.40,1.0,N,138,37,2,39.4,7.75,0.5,0.00,0.00,1.0,48.65,0.0,1.75,0.00

## NYC Yellow Taxi Trip Data Dictionary

| Field Name            | Description                                                                                                                                                                                                 |
|-----------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| VendorID              | A code indicating the TPEP provider that provided the record: 1 = Creative Mobile Technologies, LLC; 2 = Curb Mobility, LLC; 6 = Myle Technologies Inc; 7 = Helix.                                          |
| tpep_pickup_datetime  | The date and time when the meter was engaged.                                                                                                                                                               |
| tpep_dropoff_datetime | The date and time when the meter was disengaged.                                                                                                                                                            |
| passenger_count       | The number of passengers in the vehicle.                                                                                                                                                                    |
| trip_distance         | The elapsed trip distance in miles reported by the taximeter.                                                                                                                                                |
| RatecodeID            | The final rate code in effect at the end of the trip: 1 = Standard rate; 2 = JFK; 3 = Newark; 4 = Nassau or Westchester; 5 = Negotiated fare; 6 = Group ride; 99 = Null/unknown.                          |
| store_and_fwd_flag    | Indicates whether the trip record was held in vehicle memory before sending to the vendor (“store and forward”) because the vehicle did not have a connection to the server: Y = store and forward trip; N = not a store and forward trip. |
| PULocationID          | TLC Taxi Zone in which the taximeter was engaged.                                                                                                                                                           |
| DOLocationID          | TLC Taxi Zone in which the taximeter was disengaged.                                                                                                                                                        |
| payment_type          | Numeric code signifying how the passenger paid for the trip: 0 = Flex Fare trip; 1 = Credit card; 2 = Cash; 3 = No charge; 4 = Dispute; 5 = Unknown; 6 = Voided trip.                                     |
| fare_amount           | The time-and-distance fare calculated by the meter. For additional information on fare-related columns, see: https://www.nyc.gov/site/tlc/passengers/taxi-fare.page                                        |
| extra                 | Miscellaneous extras and surcharges.                                                                                                                                                                        |
| mta_tax               | Tax that is automatically triggered based on the metered rate in use.                                                                                                                                       |
| tip_amount            | Tip amount. This field is automatically populated for credit card tips; cash tips are not included.                                                                                                         |
| tolls_amount          | Total amount of all tolls paid in trip.                                                                                                                                                                     |
| improvement_surcharge | Improvement surcharge assessed on trips at the flag drop. The improvement surcharge began being levied in 2015.                                                                                            |
| total_amount          | The total amount charged to passengers. Does not include cash tips.                                                                                                                                         |
| congestion_surcharge  | Total amount collected in the trip for NYS congestion surcharge.                                                                                                                                            |
| airport_fee           | For pickups only at LaGuardia and John F. Kennedy Airports.                                                                                                                                                 |
| cbd_congestion_fee    | Per-trip charge for MTA's Congestion Relief Zone starting Jan. 5, 2025.                                                                                                                                     |

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4181444 entries, 0 to 4181443
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), object(1)
memory usage: 590.2+ MB

In [120]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,4.181444e+06,4181444,4181444,3.166704e+06,4.181444e+06,3.166704e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,4.181444e+06,3.166704e+06,3.166704e+06,4.181444e+06
mean,1.879423e+00,2025-11-15 10:46:58.380460,2025-11-15 11:05:20.075878,1.287101e+00,6.530914e+00,4.464459e+00,1.620342e+02,1.615968e+02,9.050739e-01,1.711793e+01,1.059649e+00,4.818083e-01,2.862241e+00,5.179058e-01,9.498621e-01,2.561495e+01,2.185029e+00,1.430022e-01,5.350028e-01
min,1.000000e+00,2008-12-31 23:04:21,2008-12-31 23:32:25,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-1.508700e+03,-8.500000e+00,-5.000000e-01,-3.333300e+02,-1.150500e+02,-1.000000e+00,-1.514450e+03,-2.500000e+00,-1.750000e+00,-7.500000e-01
25%,2.000000e+00,2025-11-08 00:02:02.750000,2025-11-08 00:17:31.750000,1.000000e+00,1.050000e+00,1.000000e+00,1.140000e+02,1.070000e+02,1.000000e+00,7.900000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.435000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2025-11-15 10:54:55,2025-11-15 11:08:58.500000,1.000000e+00,1.890000e+00,1.000000e+00,1.610000e+02,1.620000e+02,1.000000e+00,1.280000e+01,0.000000e+00,5.000000e-01,2.000000e+00,0.000000e+00,1.000000e+00,2.058000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2025-11-22 11:27:26.250000,2025-11-22 11:42:58.250000,1.000000e+00,3.840000e+00,1.000000e+00,2.330000e+02,2.340000e+02,1.000000e+00,2.190000e+01,2.500000e+00,5.000000e-01,4.000000e+00,0.000000e+00,1.000000e+00,3.005000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2025-11-30 23:59:59,2025-12-01 21:41:00,8.000000e+00,2.560676e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,1.508700e+03,1.500000e+01,1.050000e+01,5.750000e+02,3.000000e+02,2.500000e+00,1.514450e+03,2.500000e+00,6.750000e+00,7.500000e-01
std,7.463690e-01,NaN,NaN,7.043416e-01,6.274616e+02,1.782839e+01,6.633875e+01,7.054632e+01,6.988073e-01,1.957928e+01,1.736080e+00,1.200647e-01,4.002382e+00,2.140548e+00,2.656246e-01,2.377465e+01,9.159368e-01,5.190179e-01,3.516708e-01

### Possible questions to ask the data : 
1. What areas are the most trips have
2. Avg trip distance and the cost
3. Which vendor had the highest revenue?
4. If so which area were the trips most for these vendors?
5. What payment was the most popular?
6. What are the amount of passengers going to airport?

In [121]:
df.shape

(4181444, 20)

In [122]:
df.isna().sum()

VendorID                       0
tpep_pickup_datetime           0
tpep_dropoff_datetime          0
passenger_count          1014740
trip_distance                  0
RatecodeID               1014740
store_and_fwd_flag       1014740
PULocationID                   0
DOLocationID                   0
payment_type                   0
fare_amount                    0
extra                          0
mta_tax                        0
tip_amount                     0
tolls_amount                   0
improvement_surcharge          0
total_amount                   0
congestion_surcharge     1014740
Airport_fee              1014740
cbd_congestion_fee             0
dtype: int64

### passenger counts is null,why?

In [136]:
df[df['passenger_count'].isna()].head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
3166704,2,2025-11-01 00:17:00,2025-11-01 00:21:00,NaN,1.05,NaN,None,239,238,0,9.56,0.0,0.5,0.0,0.0,1.0,19.53,NaN,NaN,0.00
3166705,2,2025-11-01 00:27:00,2025-11-01 00:36:00,NaN,1.54,NaN,None,142,238,0,14.17,0.0,0.5,0.0,0.0,1.0,18.17,NaN,NaN,0.00
3166706,2,2025-11-01 00:26:54,2025-11-01 00:49:40,NaN,4.41,NaN,None,36,112,0,-1.98,0.0,0.5,0.0,0.0,1.0,-0.48,NaN,NaN,0.00
3166707,2,2025-11-01 00:11:00,2025-11-01 00:19:00,NaN,0.68,NaN,None,87,87,0,20.17,0.0,0.5,0.0,0.0,1.0,24.17,NaN,NaN,0.00
3166708,2,2025-11-01 00:26:00,2025-11-01 00:57:00,NaN,3.90,NaN,None,231,162,0,43.97,0.0,0.5,0.0,0.0,1.0,57.11,NaN,NaN,0.75
3166709,2,2025-11-01 00:45:34,2025-11-01 01:00:56,NaN,3.78,NaN,None,162,75,0,11.66,0.0,0.5,0.0,0.0,1.0,16.41,NaN,NaN,0.75
3166710,2,2025-11-01 00:13:32,2025-11-01 00:28:14,NaN,0.85,NaN,None,232,79,0,8.81,0.0,0.5,0.0,0.0,1.0,13.56,NaN,NaN,0.75
3166711,2,2025-11-01 00:40:22,2025-11-01 00:52:09,NaN,3.26,NaN,None,232,87,0,23.56,0.0,0.5,0.0,0.0,1.0,28.31,NaN,NaN,0.75
3166712,2,2025-11-01 00:27:47,2025-11-01 00:48:25,NaN,3.86,NaN,None,140,166,0,-9.36,0.0,0.5,0.0,0.0,1.0,-5.36,NaN,NaN,0.00
3166713,2,2025-11-01 00:51:23,2025-11-01 00:59:45,NaN,1.64,NaN,None,236,238,0,1.35,0.0,0.5,0.0,0.0,1.0,7.54,NaN,NaN,0.00

In [137]:
df.groupby("VendorID")["passenger_count"].apply(lambda x: x.isna().mean())

VendorID
1    0.168424
2    0.264629
6    1.000000
7    0.000000
Name: passenger_count, dtype: float64

In [138]:
df[df['passenger_count'].isna()]['VendorID'].value_counts()

VendorID
2    872175
1    138332
6      4233
Name: count, dtype: int64

Since other columns also are missing, it is worth checking in on them

In [139]:
cols = [
    "passenger_count",
    "RatecodeID",
    "store_and_fwd_flag",
    "congestion_surcharge",
    "Airport_fee"
]

df.groupby("VendorID")[cols].apply(lambda x: x.isna().mean())

,passenger_count,RatecodeID,store_and_fwd_flag,congestion_surcharge,Airport_fee
VendorID,,,,,
1,0.168424,0.168424,0.168424,0.168424,0.168424
2,0.264629,0.264629,0.264629,0.264629,0.264629
6,1.000000,1.000000,1.000000,1.000000,1.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000

Analysis reveals that missing values across multiple operational fields are perfectly correlated by VendorID.

Vendor 6: 100% missing across extended schema columns.

Vendor 7: 0% missing.

Vendors 1 & 2: partial missingness.

This indicates vendor-specific reporting differences rather than random data loss.

## Layer 1 — Core Metrics (All Vendors)

### Safe columns:

pickup/dropoff datetime

trip_distance

fare_amount

total_amount

tip_amount

tolls_amount

mta_tax

improvement_surcharge

Use ALL vendors for:

Demand analysis

Revenue analysis

Time patterns

Speed analysis

## Layer 2 — Extended Schema Analysis

### Only Vendors 1, 2, 7 have usable data for:

passenger_count

RatecodeID

congestion_surcharge

airport_fee

store_and_fwd_flag

So when analyzing:

Passenger behavior

Airport economics

Congestion surcharge impact

Rate code effects

--> Remove vendor 6

In [140]:
df[df['fare_amount'] < 0.00].shape

(395093, 20)

In [141]:
df.isna().mean().sort_values(ascending=False) * 100

passenger_count          24.267693
congestion_surcharge     24.267693
store_and_fwd_flag       24.267693
RatecodeID               24.267693
Airport_fee              24.267693
tpep_dropoff_datetime     0.000000
VendorID                  0.000000
tpep_pickup_datetime      0.000000
DOLocationID              0.000000
payment_type              0.000000
trip_distance             0.000000
PULocationID              0.000000
extra                     0.000000
fare_amount               0.000000
mta_tax                   0.000000
tip_amount                0.000000
improvement_surcharge     0.000000
tolls_amount              0.000000
total_amount              0.000000
cbd_congestion_fee        0.000000
dtype: float64

In [142]:
df["trip_duration_sec"] = (
    df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]
).dt.total_seconds()

In [130]:
df.shape

(4181444, 21)

In [145]:
#vendor 7 is completely getting filtered off due to trip duration checking for this
df[df["VendorID"] == 7][
    ["trip_distance", "fare_amount", "total_amount","trip_duration_sec"]
].describe()

       trip_distance   fare_amount  total_amount  trip_duration_sec
count   60043.000000  60043.000000  60043.000000            60043.0
mean        2.714508     17.026252     26.590661                0.0
std         6.353339     14.876090     19.393185                0.0
min         0.000000      0.200000      4.950000                0.0
25%         0.940000      8.600000     16.020000                0.0
50%         1.540000     12.800000     20.930000                0.0
75%         2.610000     19.100000     28.980000                0.0
max       591.120000    500.010000    501.510000                0.0

In [144]:
df[df["VendorID"] == 7]["trip_distance"].value_counts().head()

trip_distance
0.00    691
1.07    320
0.80    316
0.78    314
0.73    309
Name: count, dtype: int64

In [146]:
df[df["VendorID"] == 7][
    ["tpep_pickup_datetime", "tpep_dropoff_datetime"]
].head()

   tpep_pickup_datetime tpep_dropoff_datetime
0   2025-11-01 00:13:25   2025-11-01 00:13:25
21  2025-11-01 00:09:20   2025-11-01 00:09:20
22  2025-11-01 00:38:59   2025-11-01 00:38:59
23  2025-11-01 00:55:33   2025-11-01 00:55:33
30  2025-11-01 00:14:12   2025-11-01 00:14:12

In [131]:
df["avg_speed_mph"] = df["trip_distance"] / (df["trip_duration_sec"] / 60)

In [132]:
df = df[df["trip_duration_sec"] > 0]

In [133]:
df.groupby("VendorID")["avg_speed_mph"].describe()

,count,mean,std,min,25%,50%,75%,max
VendorID,,,,,,,,
1,820437.0,0.178401,1.043660,0.000000,0.105572,0.144578,0.199017,348.000000
2,3294654.0,0.422988,52.406897,0.000000,0.105882,0.150450,0.214169,31622.983333
6,4233.0,0.741719,19.278599,0.016409,0.157540,0.214673,0.304608,1098.600000

### Trip distance should be greater than 0

In [114]:
clean_df = df[df["trip_duration_sec"] > 0]

In [115]:
clean_df.shape

(4119324, 25)

In [116]:
clean_df['VendorID'].value_counts()

VendorID
2    3294654
1     820437
6       4233
Name: count, dtype: int64

In [96]:
clean_df['trip_distance'].max()

256067.65

In [97]:
clean_df['passenger_count'].max()

8.0

### Remove Negative Monetary Values

In [86]:
money_cols = [
    "fare_amount", "extra", "mta_tax", "tip_amount",
    "tolls_amount", "improvement_surcharge",
    "total_amount", "congestion_surcharge",
    "Airport_fee", "cbd_congestion_fee"
]

# for col in money_cols:
#     clean_df = clean_df[clean_df[col] >= 0]

In [88]:
df.groupby("VendorID")[money_cols].min()

,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
VendorID,,,,,,,,,,
1,0.0,-2.5,0.0,0.00,0.00,0.0,0.00,0.0,0.00,0.00
2,-1508.7,-8.5,-0.5,-333.33,-115.05,-1.0,-1514.45,-2.5,-1.75,-0.75
6,0.0,0.0,0.5,0.00,0.00,0.3,0.00,NaN,NaN,0.00
7,0.2,0.0,0.5,0.00,0.00,1.0,4.95,0.0,0.00,0.00

In [92]:
df.groupby(["VendorID", "payment_type_label"])["total_amount"].min()

VendorID  payment_type_label
1         Cash                     0.00
          Credit Card              0.00
          Dispute                  0.00
          Flex Fare                0.00
          No Charge                0.00
2         Cash                 -1514.45
          Credit Card           -344.53
          Dispute              -1261.31
          Flex Fare             -466.85
          No Charge             -999.88
6         Flex Fare                0.00
7         Cash                     5.20
          Credit Card              5.20
          Dispute                  5.20
          No Charge                4.95
Name: total_amount, dtype: float64

In [98]:
df["is_refund_or_adjustment"] = df["total_amount"] < 0

Negative total_amount values were observed across multiple payment types, including Cash and Credit Card. This indicates financial reversals or accounting corrections rather than data corruption.

Raw dataset retained to preserve financial integrity.

A binary is_refund_or_adjustment flag was introduced.

Analytical revenue modeling was conducted on positive-value completed trips only.

In [99]:
clean_df.shape

(4072024, 23)

In [100]:
clean_df['VendorID'].value_counts()

VendorID
2    3197644
1     810795
7      59352
6       4233
Name: count, dtype: int64

## Removing unrealistic speeds

In [106]:
clean_df = clean_df[(clean_df["avg_speed_mph"] > 1) & (clean_df["avg_speed_mph"] < 200)]

In [105]:
clean_df["avg_speed_mph"].max()

np.float64(inf)

In [107]:
clean_df.shape

(3989148, 23)

In [108]:
clean_df['VendorID'].value_counts()

VendorID
2    3176111
1     808813
6       4224
Name: count, dtype: int64

In [70]:
clean_df["calculated_total"] = (
    clean_df["fare_amount"]
    + clean_df["extra"]
    + clean_df["mta_tax"]
    + clean_df["tip_amount"]
    + clean_df["tolls_amount"]
    + clean_df["improvement_surcharge"]
    + clean_df["congestion_surcharge"]
    + clean_df["Airport_fee"]
    + clean_df["cbd_congestion_fee"]
)

(clean_df["total_amount"] - clean_df["calculated_total"]).abs().describe()

count    3.015702e+06
mean     5.734382e-01
std      1.225598e+00
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      3.552714e-15
max      5.000000e+00
dtype: float64

In [91]:
payment_map = {
    0: "Flex Fare",
    1: "Credit Card",
    2: "Cash",
    3: "No Charge",
    4: "Dispute",
    5: "Unknown",
    6: "Voided"
}

df["payment_type_label"] = df["payment_type"].map(payment_map)

In [72]:
vendor_map = {
    1: "Creative Mobile Technologies, LLC",
    2: "Curb Mobility, LLC",
    6: "Myle Technologies Inc",
    7: "Helix",
}
clean_df["vendor_map_label"] = clean_df["VendorID"].map(payment_map)

In [75]:
rate_code_map = {
    1: "Standard rate",
    2: "JFK",
    3: "Newark",
    4: "Nassau or Westchester",
    5: "Negotiated fare",
    6: "Group ride",
    99:"Null/unknown"
}
clean_df["rate_code_label"] = clean_df["RatecodeID"].map(rate_code_map)

In [76]:
clean_df.isna().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
cbd_congestion_fee       0
trip_duration_min        0
avg_speed_mph            0
calculated_total         0
payment_type_label       0
vendor_map_label         0
rate_code_label          0
dtype: int64

In [77]:
clean_df['VendorID'].value_counts()

VendorID
2    2343204
1     672498
Name: count, dtype: int64

In [78]:
df['VendorID'].value_counts()

VendorID
2    3295835
1     821333
7      60043
6       4233
Name: count, dtype: int64

In [80]:
df[(df["avg_speed_mph"] > 1) & (df["avg_speed_mph"] < 140)]['VendorID'].value_counts()

VendorID
2    3176088
1     808684
6       4222
Name: count, dtype: int64

In [82]:
for col in money_cols:
     print(df[df[col] >= 0]['VendorID'].value_counts())

VendorID
2    2900742
1     821333
7      60043
6       4233
Name: count, dtype: int64
VendorID
2    3273210
1     821033
7      60043
6       4233
Name: count, dtype: int64
VendorID
2    3249963
1     821333
7      60043
6       4233
Name: count, dtype: int64
VendorID
2    3295763
1     821333
7      60043
6       4233
Name: count, dtype: int64
VendorID
2    3291243
1     821333
7      60043
6       4233
Name: count, dtype: int64
VendorID
2    3247447
1     821333
7      60043
6       4233
Name: count, dtype: int64
VendorID
2    3168916
1     821333
7      60043
6       4233
Name: count, dtype: int64
VendorID
2    2385475
1     683001
7      60043
Name: count, dtype: int64
VendorID
2    2413108
1     683001
7      60043
Name: count, dtype: int64
VendorID
2    3263691
1     821333
7      60043
6       4233
Name: count, dtype: int64